from twisted.internet import defer, reactor

from raindrop.tests import TestCaseWithCorpus

class ConvoTestCase(TestCaseWithCorpus):
    @defer.inlineCallbacks
    def setUp(self):
        _ = yield TestCaseWithCorpus.setUp(self)
        ndocs = yield self.load_corpus('hand-rolled')

class TestSimpleCorpus(TestCaseWithCorpus):
    def ensure_doc(self, doc, expected_doc):
        # Generate a list of the properties of the document.
        # We ignore private properties of CouchDB (start with underscore)
        # and Raindrop (start with "rd_"), as we are only testing the public
        # properties generated by our extension.
        actual_properties = sorted([key for key in doc.keys()
                                        if not key.startswith('_')
                                        and not key.startswith('rd_')])

        expected_properties = sorted([key for key in expected_doc.keys()])

        # The document should have the expected properties.
        self.failUnlessEqual(actual_properties, expected_properties,
                             repr(doc['rd_key']) + ' properties')

        # The document's properties should have the expected values.
        for property in expected_doc:
            self.failUnlessEqual(doc[property], expected_doc[property],
                                 repr(doc['rd_key']) + '::' + property)

    @defer.inlineCallbacks
    def get_docs(self, key, expected=None):
        result = yield self.doc_model.open_view(key=key, reduce=False,
                                                include_docs=True)
        rows = result['rows']
        if expected is not None:
            self.failUnlessEqual(len(rows), expected,
                                 'num rows for key ' + repr(key))
        docs = [row['doc'] for row in rows]
        defer.returnValue(docs)

    @defer.inlineCallbacks
    def put_docs(self, corpus_name, corpus_spec="*", expected=None):
        items = [d for d in self.gen_corpus_schema_items(corpus_name, corpus_spec)]
        if expected is not None:
            self.failUnlessEqual(len(items), expected)
        _ = yield self.doc_model.create_schema_items(items)
        _ = yield self.ensure_pipeline_complete()

    @defer.inlineCallbacks
    def test_convo_single(self):
        # Initialize the corpus & database.
        yield self.init_corpus('hand-rolled')

        # Process a single item - should get its own convo
        yield self.put_docs('hand-rolled', 'sent-email-simple', 1)

        msgid = ['email', 'd3d08a8a534c464881a95b75300e9011@something']
        body_schema = (yield self.doc_model.open_schemas([(msgid, 'rd.msg.body')]))[0]
        # should be one 'rd.convo.messages' and one 'rd.convo.summary' doc
        # in total in the DB.
        keys = [['rd.core.content', 'schema_id', 'rd.conv.messages'],
                ['rd.core.content', 'schema_id', 'rd.conv.summary'],
            ]
        result = yield self.doc_model.open_view(keys=keys, reduce=False,
                                                include_docs = True)
        rows = result['rows']
        self.failUnlessEqual(len(rows), 2, str(rows))
        # results should be ordered by key, so .messages first.
        self.failUnlessEqual(rows[0]['doc']['rd_schema_id'], 'rd.conv.messages')
        self.failUnlessEqual(rows[1]['doc']['rd_schema_id'], 'rd.conv.summary')
        doc_msgs = rows[0]['doc']
        doc_sum = rows[1]['doc']
        ## The document should have the expected properties/values.
        expected_doc = {
            'messages': [msgid]
        }
        self.ensure_doc(doc_msgs, expected_doc)
        expected_doc = {
            'earliest_timestamp': body_schema['timestamp'],
            'latest_timestamp': body_schema['timestamp'],
            'recent': [msgid],
            'messages': [msgid],
            'target-timestamp': [['from', body_schema['timestamp']]],
            'identities': [['email', 'raindrop_test_recip2@mozillamessaging.com'],
                           ['email', 'raindrop_test_recip3@mozillamessaging.com'],
                           ['email', 'raindrop_test_recip@mozillamessaging.com'],
                           ['email', 'raindrop_test_user@mozillamessaging.com'],
                            ],
            'num_unread': 1,
        }
        self.ensure_doc(doc_sum, expected_doc)

    @defer.inlineCallbacks
    def test_convo_deleted(self):
        _ = yield self.test_convo_single()
        # now make our one message 'deleted'.
        msgid = ['email', 'd3d08a8a534c464881a95b75300e9011@something']
        si = {
            'rd_key': msgid,
            'rd_schema_id': 'rd.msg.deleted',
            'rd_ext_id': 'rd.testsuite',
            'items' : {
                'deleted': True,
                'outgoing_state': 'outgoing',
            }
        }
        _ = yield self.doc_model.create_schema_items([si])
        _ = yield self.ensure_pipeline_complete()
        # should be one 'rd.convo.messages' and one 'rd.convo.summary' doc
        # in total in the DB.
        keys = [['rd.core.content', 'schema_id', 'rd.conv.messages'],
                ['rd.core.content', 'schema_id', 'rd.conv.summary'],
            ]
        result = yield self.doc_model.open_view(keys=keys, reduce=False,
                                                include_docs = True)
        rows = result['rows']
        self.failUnlessEqual(len(rows), 2, str(rows))
        # results should be ordered by key, so .messages first.
        self.failUnlessEqual(rows[0]['doc']['rd_schema_id'], 'rd.conv.messages')
        self.failUnlessEqual(rows[1]['doc']['rd_schema_id'], 'rd.conv.summary')
        doc_msgs = rows[0]['doc']
        doc_sum = rows[1]['doc']
        expected_doc = {
            'earliest_timestamp': None,
            'latest_timestamp': None,
            'target-timestamp': [],
            'recent': [],
            'messages': [],
            'identities': [],
            'num_unread': 0,
        }
        self.ensure_doc(doc_sum, expected_doc)

    @defer.inlineCallbacks
    def test_convo_multiple(self):
        msgid = ['email', 'd3d08a8a534c464881a95b75300e9011@something']
        msgid_reply = ['email', '78cb2eb5dbc74cdd9691dcfdb266d1b9@something']
        _ = yield self.test_convo_single()
        # add the reply.
        yield self.put_docs('hand-rolled', 'sent-email-simple-reply', 1)

        body_orig, body_reply = (yield self.doc_model.open_schemas(
                                    [(msgid, 'rd.msg.body'),
                                     (msgid_reply, 'rd.msg.body'),
                                        ]))
        # should still be exactly one convo referencing both messages.
        keys = [['rd.core.content', 'schema_id', 'rd.conv.messages'],
                ['rd.core.content', 'schema_id', 'rd.conv.summary'],
            ]
        result = yield self.doc_model.open_view(keys=keys, reduce=False,
                                                include_docs = True)
        rows = result['rows']
        self.failUnlessEqual(len(rows), 2, str(rows))
        # results should be ordered by key, so .messages first.
        self.failUnlessEqual(rows[0]['doc']['rd_schema_id'], 'rd.conv.messages')
        self.failUnlessEqual(rows[1]['doc']['rd_schema_id'], 'rd.conv.summary')
        doc_msgs = rows[0]['doc']
        doc_sum = rows[1]['doc']
        ## The document should have the expected properties/values.
        expected_doc = {
            'messages': sorted([msgid, msgid_reply]),
        }
        self.ensure_doc(doc_msgs, expected_doc)
        expected_doc = {
            'earliest_timestamp': min(body_orig['timestamp'], body_reply['timestamp']),
            'latest_timestamp': max(body_orig['timestamp'], body_reply['timestamp']),
            'recent': sorted([msgid, msgid_reply]),
            'messages': sorted([msgid, msgid_reply]),
            'target-timestamp': [['direct', body_reply['timestamp']], ['from', body_orig['timestamp']]],
            'identities': [['email', 'raindrop_test_recip2@mozillamessaging.com'],
                           ['email', 'raindrop_test_recip3@mozillamessaging.com'],
                           ['email', 'raindrop_test_recip@mozillamessaging.com'],
                           ['email', 'raindrop_test_user@mozillamessaging.com'],
                            ],
            'num_unread': 2,
        }
        self.ensure_doc(doc_sum, expected_doc)
